package org.testadirapa.sesterzo.exceptions

enum class ExceptionLabel {
	AttachmentNotFound,
	BudgetNotFound,
	BudgetUpdateFailed,
	BudgetElementNotFound,
	CannotDecryptWithAesKey,
	CannotDecryptWithRsaKey,
	CannotEncryptWithAesKey,
	ExpenseDeletionFailed,
	ForbiddenInSpace,
	GenericForbidden,
	ImageTooLarge,
	InvalidCaptcha,
	InvalidJwt,
	InvalidKeyFormat,
	InvalidRegistration,
	InvalidRegistrationParameters,
	InvalidPrivateKey,
	MissingSpaceKey,
	PublicKeyUpdateFailed,
	QuotaExceeded,
	RecoveryKeyExpired,
	RecoveryKeyNotFound,
	SpaceNotFound,
	SpaceThumbnailUpdateFailed,
	Unauthorized,
	UserNotFound,
	UserUpdateFailed
}