ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [org.testadirapa.sesterzo.ApplicationKt.module]
    }
    environment = ${?KTOR_ENV}
    environment = "dev"

    jwt {
        authPrivateKey = ${AUTH_PRIVATE_KEY}
       	authPublicKey = ${AUTH_PUBLIC_KEY}
        refreshPrivateKey = ${REFRESH_PRIVATE_KEY}
       	refreshPublicKey = ${REFRESH_PUBLIC_KEY}
        issuer = "http://0.0.0.0:8080/"
        audience = "http://0.0.0.0:8080"
        realm = "Access to 'sesterzo'"
    }
}

mongodb {
    username = ${MONGODB_USERNAME}
    password = ${MONGODB_PASSWORD}
    ip = ${MONGODB_IP}
    port = ${MONGODB_PORT}
    databaseName = ${MONGODB_DATABASE}
}

mailer {
    sesterzoUrl = ${?SESTERZO_URL}
    hermesUrl = ${?HERMES_URL}
    registrationTemplateId = ${?REGISTRATION_TEMPLATE_ID}
    tokenTemplateId = ${?TOKEN_TEMPLATE_ID}
}