name: sesterzo

services:
    mongodb:
        image: mongo:8.2
        restart: always
        command: [--auth, --replSet, repl0, --bind_ip_all, "--keyFile", "/data/key.key"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN_USR}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMIN_PWD}
            MONGO_INITDB_DATABASE: sesterzo
        logging:
            driver: "json-file"
            options:
                max-file: 5
                max-size: 15m
        ports:
            - "27018:27017"
        networks:
            - mongo-network
        volumes:
            - ${MONGODB_FOLDER}/seed/data/key.key:/data/key.key
        healthcheck:
            test: mongosh --username ${MONGODB_ADMIN_USR} --password ${MONGODB_ADMIN_PWD} --authenticationDatabase admin
            interval: 15s
            timeout: 5s
            retries: 5

    mongodb-init:
        build: ./mongoinit
        depends_on:
            mongodb:
                condition: service_healthy
        networks:
            - mongo-network
        environment:
            MONGODB_ADMIN_USR: ${MONGODB_ADMIN_USR}
            MONGODB_ADMIN_PWD: ${MONGODB_ADMIN_PWD}
            MONGODB_HOST: mongodb
            HOMUNCULUS_DB: ${HOMUNCULUS_DB}

    hermes:
        image: lotuxpunk/hermes:latest
        restart: always
        networks:
            - mongo-network
        volumes:
            - ${HERMES_FOLDER}/forms:/hermes/config/forms
            - ${HERMES_FOLDER}/mails:/hermes/config/mails
            - ${HERMES_FOLDER}/templates:/hermes/config/templates
        environment:
            CONTACT_FORM_CONFIGS_FOLDER: /hermes/config/forms
            MAIL_CONFIGS_FOLDER: /hermes/config/mails
            TEMPLATES_FOLDER: /hermes/config/templates

    sesterzo-backend:
        image: sesterzo-backend:${GIT_COMMIT}
        build:
            context: ..
            dockerfile: deployment/sesterzo-backend/Dockerfile
        depends_on:
            - hermes
            - mongodb-init
        restart: always
        networks:
            - mongo-network
        environment:
            AUTH_PRIVATE_KEY: ${AUTH_PRIVATE_KEY}
            AUTH_PUBLIC_KEY: ${AUTH_PUBLIC_KEY}
            REFRESH_PRIVATE_KEY: ${REFRESH_PRIVATE_KEY}
            REFRESH_PUBLIC_KEY: ${REFRESH_PUBLIC_KEY}
            MONGODB_DATABASE: sesterzo
            MONGODB_IP: mongodb
            MONGODB_PORT: 27017
            MONGODB_USERNAME: ${MONGODB_ADMIN_USR}
            MONGODB_PASSWORD: ${MONGODB_ADMIN_PWD}
            SESTERZO_URL: "https://sesterzo.eu"
            HERMES_URL: "http://hermes:8081"
            REGISTRATION_TEMPLATE_ID: "authentication_email"
            TOKEN_TEMPLATE_ID: "authentication_email"

    sesterzo-frontend:
        image: sesterzo-frontend:${GIT_COMMIT}
        build:
            context: ..
            dockerfile: deployment/sesterzo-frontend/Dockerfile
        depends_on:
            - sesterzo-backend
        restart: always
        networks:
            - mongo-network
        ports:
            - "8083:80"

networks:
    mongo-network:
        driver: bridge