#!/usr/bin/env python3
"""Regenerate the Android launcher icon from the Inkscape source in assets/.

The three assets/icon_*.svg files are the same Inkscape document with different
layer visibility, so this script only reads ONE of them (the source) and toggles
the layers itself. That keeps the generated icon consistent even if you edit just
one of the files.

It produces, under androidApp/src/main/res/:
  drawable/ic_launcher_background.xml   <- LAYERS['background']
  drawable/ic_launcher_foreground.xml   <- LAYERS['foreground']
  drawable/ic_launcher_monochrome.xml   <- LAYERS['monochrome']
  mipmap-anydpi-v26/ic_launcher.xml, ic_launcher_round.xml
  mipmap-*/ic_launcher.png, ic_launcher_round.png   (legacy pre-API-26 raster)

Requirements:
  * Android Studio, for its bundled SVG -> VectorDrawable converter (Svg2Vector)
    and JBR. Override the search with ANDROID_STUDIO_HOME / JAVA_HOME.
  * rsvg-convert, for the legacy raster icons (`brew install librsvg`).
    Skip that step with --skip-legacy if you do not have it.

Usage:
  tools/update_android_icon.py                # regenerate everything and verify
  tools/update_android_icon.py --no-verify    # skip the Gradle resource check
  tools/update_android_icon.py --preview DIR  # also write composited PNG previews
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RES = REPO / "androidApp" / "src" / "main" / "res"

# Inkscape layer ids in the source document. If you add or rename layers in
# Inkscape, update these -- the script fails loudly rather than silently
# generating a wrong icon.
LAYERS = {
    "background": "layer4",  # dark base + the two radial glows
    "foreground": "layer2",  # the gradient "S" mark
    "monochrome": "layer8",  # flat silhouette, for themed icons
}
# Annotation/guide layer: always hidden in Inkscape, and dropped entirely before
# conversion because it contains <text>, which vector drawables cannot express.
GUIDE_LAYER = "layer3"

# Adaptive icons are a 108dp canvas of which only the central 72dp is guaranteed
# visible. Legacy (pre-API-26) launchers get that 72dp square rasterised.
CANVAS_DP = 108
CONTENT_DP = 72
# Legacy icon size per density bucket, in px.
DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}

ADAPTIVE_ICON = """<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""

GENERATED_NOTE = "<!-- Generated by tools/update_android_icon.py from assets/. Do not edit by hand. -->"


def fail(msg: str) -> "NoReturn":  # type: ignore[valid-type]
    sys.exit(f"error: {msg}")


def info(msg: str) -> None:
    print(f"  {msg}")


# --------------------------------------------------------------------------
# SVG surgery: we edit the raw text rather than round-tripping through an XML
# parser, so everything we do not touch stays byte-for-byte identical (and the
# Inkscape/xlink namespace prefixes the converter relies on survive intact).
# --------------------------------------------------------------------------

def _find_group_tag(svg: str, layer_id: str) -> tuple[int, int]:
    """Return the (start, end) span of the opening <g> tag carrying layer_id."""
    for m in re.finditer(r"<g\b[^>]*>", svg):
        if re.search(rf'\bid="{re.escape(layer_id)}"', m.group(0)):
            return m.span()
    fail(
        f'layer id "{layer_id}" not found in the source SVG. '
        "If you renamed layers in Inkscape, update LAYERS/GUIDE_LAYER in this script."
    )


def set_layer_visible(svg: str, layer_id: str, visible: bool) -> str:
    """Force a layer's CSS display to inline or none."""
    start, end = _find_group_tag(svg, layer_id)
    tag = svg[start:end]
    want = "inline" if visible else "none"

    style = re.search(r'style="([^"]*)"', tag)
    if style:
        decls = [d for d in style.group(1).split(";") if d.strip()]
        decls = [d for d in decls if not d.strip().startswith("display")]
        decls.insert(0, f"display:{want}")
        new_tag = tag[: style.start(1)] + ";".join(decls) + tag[style.end(1) :]
    else:
        new_tag = tag[:-1].rstrip() + f' style="display:{want}">'
    return svg[:start] + new_tag + svg[end:]


def drop_layer(svg: str, layer_id: str) -> str:
    """Remove a whole <g> element (and its children) by layer id."""
    start, open_end = _find_group_tag(svg, layer_id)
    if svg[open_end - 2 : open_end] == "/>":  # empty element
        return svg[:start] + svg[open_end:]
    depth, pos = 1, open_end
    for m in re.finditer(r"<g\b[^>]*?(/?)>|</g\s*>", svg[open_end:]):
        pos = open_end + m.end()
        if m.group(0).startswith("</g"):
            depth -= 1
            if depth == 0:
                return svg[:start] + svg[pos:]
        elif not m.group(1):  # an opening <g>, not self-closing
            depth += 1
    fail(f'unbalanced <g> tags while removing layer "{layer_id}"')


def variant_svg(source: str, visible: set[str]) -> str:
    """Source SVG with only `visible` layers shown and the guide layer removed."""
    svg = drop_layer(source, GUIDE_LAYER)
    for layer_id in LAYERS.values():
        svg = set_layer_visible(svg, layer_id, layer_id in visible)
    return svg


def viewbox(svg: str) -> tuple[float, float, float, float]:
    m = re.search(r'viewBox="([-\d.eE\s]+)"', svg)
    if not m:
        fail("source SVG has no viewBox")
    parts = [float(v) for v in m.group(1).split()]
    if len(parts) != 4:
        fail(f"unexpected viewBox: {m.group(1)!r}")
    return tuple(parts)  # type: ignore[return-value]


def check_siblings(source_path: Path, source: str) -> None:
    """Warn if the other icon_*.svg files differ by more than layer visibility.

    They are meant to be the same document, so a real divergence means edits
    landed in a file this script does not read.
    """
    def normalise(text: str) -> str:
        out = drop_layer(text, GUIDE_LAYER)
        for layer_id in LAYERS.values():
            out = set_layer_visible(out, layer_id, False)
        return out

    base = normalise(source)
    for sibling in sorted(source_path.parent.glob("icon_*.svg")):
        if sibling == source_path:
            continue
        if normalise(sibling.read_text()) != base:
            print(
                f"warning: {sibling.name} differs from {source_path.name} beyond layer\n"
                f"         visibility. Only {source_path.name} was used; re-export the\n"
                f"         others from Inkscape so they stay in sync.",
                file=sys.stderr,
            )


# --------------------------------------------------------------------------
# SVG -> VectorDrawable, via Android Studio's own converter
# --------------------------------------------------------------------------

CONVERTER_SRC = r"""
import com.android.ide.common.vectordrawable.Svg2Vector;
import java.io.*;
import java.nio.file.*;
import java.lang.reflect.*;

public class Svg2VectorCli {
  public static void main(String[] args) throws Exception {
    Path in = Paths.get(args[0]);
    try (OutputStream os = new FileOutputStream(args[1])) {
      for (Method m : Svg2Vector.class.getMethods()) {
        if (m.getName().equals("parseSvgToXml") && m.getParameterCount() == 2) {
          Object arg = m.getParameterTypes()[0] == File.class ? in.toFile() : in;
          Object errors = m.invoke(null, arg, os);
          if (errors != null && !errors.toString().isEmpty()) {
            System.err.println(errors);
            System.exit(2);
          }
          return;
        }
      }
      System.err.println("no usable Svg2Vector.parseSvgToXml overload found");
      System.exit(3);
    }
  }
}
"""


def studio_home() -> Path:
    override = os.environ.get("ANDROID_STUDIO_HOME")
    candidates = [Path(override)] if override else []
    candidates += [
        Path("/Applications/Android Studio.app"),
        Path.home() / "Applications" / "Android Studio.app",
        Path("/usr/local/android-studio"),
        Path("/opt/android-studio"),
    ]
    for path in candidates:
        if (path / "Contents" / "plugins" / "android" / "lib").is_dir():
            return path / "Contents"
        if (path / "plugins" / "android" / "lib").is_dir():  # Linux layout
            return path
    fail(
        "could not find Android Studio (needed for its SVG->VectorDrawable "
        "converter). Set ANDROID_STUDIO_HOME to its install path."
    )


def java_binary(studio: Path) -> str:
    if os.environ.get("JAVA_HOME"):
        candidate = Path(os.environ["JAVA_HOME"]) / "bin" / "java"
        if candidate.is_file():
            return str(candidate)
    for rel in ("jbr/Contents/Home/bin/java", "jbr/bin/java"):
        candidate = studio / rel
        if candidate.is_file():
            return str(candidate)
    found = shutil.which("java")
    if found:
        return found
    fail("no Java runtime found; set JAVA_HOME")


class Converter:
    """Compiles the tiny Svg2Vector driver once, then reuses it."""

    def __init__(self, workdir: Path) -> None:
        studio = studio_home()
        self.java = java_binary(studio)
        jars = sorted((studio / "plugins" / "android" / "lib").glob("*.jar"))
        jars += sorted((studio / "lib").glob("*.jar"))
        if not any(j.name == "sdk-common.jar" for j in jars):
            fail(f"sdk-common.jar not found under {studio} -- unexpected Android Studio layout")
        self.classes = workdir / "classes"
        self.classes.mkdir()
        src = workdir / "Svg2VectorCli.java"
        src.write_text(CONVERTER_SRC)
        self.classpath = os.pathsep.join(str(j) for j in jars)
        javac = Path(self.java).with_name("javac")
        if not javac.is_file():
            fail(f"javac not found next to {self.java}")
        run = subprocess.run(
            [str(javac), "-cp", self.classpath, "-d", str(self.classes), str(src)],
            capture_output=True,
            text=True,
        )
        if run.returncode != 0:
            fail(f"could not compile the SVG converter:\n{run.stderr.strip()}")

    def convert(self, svg_path: Path, out_path: Path) -> None:
        run = subprocess.run(
            [
                self.java,
                "-cp", os.pathsep.join([self.classpath, str(self.classes)]),
                "Svg2VectorCli", str(svg_path), str(out_path),
            ],
            capture_output=True,
            text=True,
        )
        if run.returncode != 0:
            fail(f"converting {svg_path.name} failed:\n{run.stderr.strip()}")


# --------------------------------------------------------------------------
# VectorDrawable post-processing
# --------------------------------------------------------------------------

# A <path> whose geometry is an open line (no curves, arcs or close) and whose
# stroke is transparent paints nothing. Inkscape leaves a couple of these behind
# as construction lines; they are noise in the drawable.
_PATH_BLOCK = re.compile(r"[ \t]*<path\b.*?/>\n", re.S)


def strip_invisible_paths(xml: str) -> tuple[str, int]:
    def is_noop(block: str) -> bool:
        data = re.search(r'android:pathData="([^"]*)"', block)
        if not data:
            return False
        geometry = data.group(1)
        if re.search(r"[CcSsQqTtAaZz]", geometry):
            return False  # a real (closeable) shape
        stroke = re.search(r'android:strokeColor="([^"]*)"', block)
        transparent = stroke is not None and stroke.group(1).lower() in {
            "#00000000", "@android:color/transparent",
        }
        return transparent or stroke is None

    removed = 0

    def replace(m: re.Match[str]) -> str:
        nonlocal removed
        if is_noop(m.group(0)):
            removed += 1
            return ""
        return m.group(0)

    return _PATH_BLOCK.sub(replace, xml), removed


def force_black(xml: str) -> str:
    """Themed icons tint the monochrome layer, so only its alpha matters.

    Normalising the fills to opaque black makes that explicit and keeps the
    drawable stable when the artwork's colours change.
    """
    return re.sub(r'android:fillColor="#[0-9a-fA-F]{3,8}"', 'android:fillColor="#FF000000"', xml)


def add_header(xml: str) -> str:
    if xml.startswith("<?xml"):
        first, _, rest = xml.partition("\n")
        return f"{first}\n{GENERATED_NOTE}\n{rest}"
    return f"{GENERATED_NOTE}\n{xml}"


def write_if_changed(path: Path, text: str) -> bool:
    if path.is_file() and path.read_text() == text:
        info(f"unchanged {path.relative_to(REPO)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    info(f"wrote     {path.relative_to(REPO)}")
    return True


# --------------------------------------------------------------------------
# Legacy raster icons
# --------------------------------------------------------------------------

def legacy_svgs(source: str, workdir: Path) -> tuple[Path, Path]:
    """Composite background+foreground, cropped to the 72dp content square.

    Returns (square, round) SVG paths; the round one is clipped to the inscribed
    circle the way a legacy round launcher icon would be.
    """
    composite = variant_svg(source, {LAYERS["background"], LAYERS["foreground"]})

    x, y, w, h = viewbox(composite)
    scale = CONTENT_DP / CANVAS_DP
    cw, ch = w * scale, h * scale
    cx, cy = x + (w - cw) / 2, y + (h - ch) / 2
    square = re.sub(
        r'viewBox="[-\d.eE\s]+"', f'viewBox="{cx:g} {cy:g} {cw:g} {ch:g}"', composite, count=1
    )
    square_path = workdir / "legacy_square.svg"
    square_path.write_text(square)

    clip_id = "legacyRoundClip"
    clip = (
        f'<clipPath id="{clip_id}" clipPathUnits="userSpaceOnUse">'
        f'<circle cx="{cx + cw / 2:g}" cy="{cy + ch / 2:g}" r="{min(cw, ch) / 2:g}" />'
        f"</clipPath>"
    )
    m = re.search(r"<defs\b[^>]*>", square)
    if m:
        rounded = square[: m.end()] + clip + square[m.end() :]
    else:
        m = re.search(r"<svg\b[^>]*>", square)
        rounded = square[: m.end()] + f"<defs>{clip}</defs>" + square[m.end() :]
    for layer_id in (LAYERS["background"], LAYERS["foreground"]):
        start, end = _find_group_tag(rounded, layer_id)
        rounded = (
            rounded[:start]
            + rounded[start:end][:-1].rstrip()
            + f' clip-path="url(#{clip_id})">'
            + rounded[end:]
        )
    round_path = workdir / "legacy_round.svg"
    round_path.write_text(rounded)
    return square_path, round_path


def render(svg: Path, png: Path, size: int) -> None:
    png.parent.mkdir(parents=True, exist_ok=True)
    run = subprocess.run(
        ["rsvg-convert", "-w", str(size), "-h", str(size), "-o", str(png), str(svg)],
        capture_output=True,
        text=True,
    )
    if run.returncode != 0:
        fail(f"rsvg-convert failed for {svg.name}:\n{run.stderr.strip()}")


# --------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the Android launcher icon from assets/icon_*.svg."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=REPO / "assets" / "icon_background.svg",
        help="source Inkscape SVG (all layers are read from this one file)",
    )
    parser.add_argument(
        "--skip-legacy", action="store_true",
        help="do not regenerate the pre-API-26 mipmap PNGs (skips the rsvg-convert dependency)",
    )
    parser.add_argument(
        "--no-verify", action="store_true",
        help="do not run the Gradle resource-linking check afterwards",
    )
    parser.add_argument(
        "--preview", type=Path, metavar="DIR",
        help="also write composited PNG previews here for eyeballing",
    )
    args = parser.parse_args()

    if not args.source.is_file():
        fail(f"source SVG not found: {args.source}")
    source = args.source.read_text()

    print(f"Source: {args.source.relative_to(REPO) if args.source.is_relative_to(REPO) else args.source}")
    check_siblings(args.source.resolve(), source)

    need_raster = not args.skip_legacy or args.preview
    if need_raster and not shutil.which("rsvg-convert"):
        fail(
            "rsvg-convert not found (needed for the legacy raster icons).\n"
            "       Install it with `brew install librsvg`, or pass --skip-legacy."
        )

    with tempfile.TemporaryDirectory(prefix="icon-gen-") as tmp:
        workdir = Path(tmp)

        print("Converting layers to vector drawables")
        converter = Converter(workdir)
        changed = False
        for name, layer_id in LAYERS.items():
            svg_path = workdir / f"{name}.svg"
            svg_path.write_text(variant_svg(source, {layer_id}))
            xml_path = workdir / f"{name}.xml"
            converter.convert(svg_path, xml_path)

            xml, removed = strip_invisible_paths(xml_path.read_text())
            if removed:
                info(f"dropped {removed} non-painting path(s) from {name}")
            if name == "monochrome":
                xml = force_black(xml)
            changed |= write_if_changed(
                RES / "drawable" / f"ic_launcher_{name}.xml", add_header(xml)
            )

        print("Wiring up the adaptive icons")
        for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
            changed |= write_if_changed(RES / "mipmap-anydpi-v26" / name, ADAPTIVE_ICON)

        if not args.skip_legacy:
            print("Rendering legacy (pre-API-26) mipmaps")
            square, rounded = legacy_svgs(source, workdir)
            for bucket, size in DENSITIES.items():
                render(square, RES / f"mipmap-{bucket}" / "ic_launcher.png", size)
                render(rounded, RES / f"mipmap-{bucket}" / "ic_launcher_round.png", size)
            info(f"{2 * len(DENSITIES)} PNGs across {', '.join(DENSITIES)}")
            changed = True  # PNGs are rewritten unconditionally
        else:
            print("Skipping legacy mipmaps (--skip-legacy)")

        if args.preview:
            square, rounded = legacy_svgs(source, workdir)
            args.preview.mkdir(parents=True, exist_ok=True)
            render(square, args.preview / "icon_square.png", 512)
            render(rounded, args.preview / "icon_round.png", 512)
            full = workdir / "preview_full.svg"
            full.write_text(variant_svg(source, {LAYERS["background"], LAYERS["foreground"]}))
            render(full, args.preview / "icon_full_canvas.png", 432)
            print(f"Previews in {args.preview}")

    # AGP's incremental resource merger can produce a stale merge after resources
    # are added or removed -- and it caches that bad output. Dropping the merged
    # resource intermediates forces a clean merge on the next build.
    for stale in ("merged_res", "packaged_res", "incremental"):
        target = REPO / "androidApp" / "build" / "intermediates" / stale
        if target.exists():
            shutil.rmtree(target)
            info(f"cleared stale androidApp/build/intermediates/{stale}")

    if args.no_verify:
        print("\nDone (skipped verification). Build the app to pick up the new icon.")
        return 0

    print("\nVerifying that the resources link")
    gradlew = REPO / "gradlew"
    run = subprocess.run(
        [str(gradlew), ":androidApp:processDebugResources", "--console=plain"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    if run.returncode != 0:
        tail = "\n".join((run.stdout + run.stderr).strip().splitlines()[-25:])
        fail(f"Gradle could not link the new resources:\n{tail}")
    print("Done. Resources link cleanly." if changed else "Done. Nothing changed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
